language: php

php:
  - 5.6
  - 7.0
  - nightly

sudo: false

cache:
   directories:
     - $HOME/.composer/cache/files

script:
    - ant -f build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-continuous static-lint

notifications:
    email: false
    irc: "chat.freenode.net#shopware-dev"

matrix:
  allow_failures:
    - php: nightly
  include:
    - addons:
      mariadb: 5.5
    - addons:
      mariadb: 10.0
    - addons:
      mariadb: 10.1
